name: Build .NET

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: microsoft/setup-msbuild@v1
    - uses: nuget/setup-nuget@v1
    - run: nuget restore "Hearth Arena Uploader.sln"
    - name: Build .NET
      run: |
        MSBuild.exe "Hearth Arena Uploader.sln"
